      PROGRAM CAL(INPUT,OUTPUT)
CCC
CCC   PROGRAM PRINTS DATES AT 64 DAY INTERVALS FROM AN INITIAL
CCC   DATE FOR A PERIOD OF ABOUT 67 YEARS (384 INTERVALS).
CCC   USES SUBROUTINE DATE TO CONVERT DAY NUMBER TO DAY AND MONTH.
CCC
      INTEGER DAY, YEAR
      INTEGER DAYNUM, DAYSPRV ,AYEAR
      DIMENSION DAYSPRV(12), NAME(12)
      DATA DAYSPRV/306,337,0,31,61,92,122,153,184,214,245,275/
      DATA NAME/3HJAN,3HFEB,3HMAR,3HAPR,3HMAY,3HJUN,3HJUL,3HAUG,3HSEP,
     +    3HOCT,3HNOV,3HDEC/
CCC
CCC   READ INITIAL DATE
CCC   YEARS B.C. ASSUMED PRECEDED BY MINUS SIGN
CCC
      READ 1, DAY, MONTH, YEAR
 1    FORMAT(12,1X,12,1X,15)
CCC
CCC   CONVERT DATE TO DAY NUMBER IN YEAR, ADJUSTING YEAR
CCC
      AYEAR = YEAR
C
C     ADJUST COMMON YEAR TO ASTRONOMICAL YEAR FOR YEARS B.C.
C     (I.E. 1 B.C. BECOMES YEAR 0, ETC.)
C
      IF (YEAR.LT.0) AYEAR = AYEAR + 1
C
C     COMPUTE DAY NUMBER OF INITIAL DATE
C     FROM PRECEDING MARCH 1
C
      DAYNUM = DAY + DAYSPRV(MONTH)
C
C     AND ADJUST YEAR NUMBER
C
      IF (MONTH.GT.2) AYEAR = AYEAR + 1
CCC
CCC   PRINT TITLE
CCC
      PRINT 2
 2    FORMAT(1H1,*       TABLE OF DATES AND POSITIONS        *//)
CCC
CCC   COMPUTE AND PRINT DATES
CCC
      DO 3000 I=1,384
      PRINT 3,I,DAY,NAME(MONTH),YEAR
 3    FORMAT(1X,I3,5X,I2,1X,A3,1X,I5)
      DAYNUM = DAYNUM + 64
C
C     ADJUST FOR CALENDAR REFORM
C     10 DAYS LOST BETWEEN OCT. 5 AND 10, 1582
C
      IF(AYEAR.NE.1583) GO TO 2200
      IF (DAYNUM.GT.218) DAYNUM = DAYNUM + 10
 2200 CONTINUE
C
C     ADJUST FOR NEW YEAR
C
      IF (DAYNUM.LT.366) GO TO 2100
      IF ((MOD(AYEAR,4).EQ.0).AND.((MOD(AYEAR,100).NE.0).OR.
     +  (MOD(AYEAR,400).EQ.0))) GO TO 2050
      DAYNUM = DAYNUM - 365
      GO TO 2090
 2050 CONTINUE
C
C     LEAP YEAR
C
      IF (DAYNUM.EQ.366) GO TO 2100
      DAYNUM = DAYNUM - 366
 2090 CONTINUE
      AYEAR = AYEAR + 1
 2100 CONTINUE
      CALL DATE(DAYNUM,AYEAR,DAY,MONTH,YEAR)
      IF (YEAR.LT.1) YEAR = YEAR - 1
 3000 CONTINUE
      STOP
      END

