      SUBROUTINE DATE(DAYNUM,AYEAR,DAY,MONTH,YEAR)
CCC
CCC   SUBROUNTE TO COMPUTE DATE GIVEN DAY OF YEAR.
CCC   BEGINNING OF YEAR ASSUMED ADJUSTED TO PRECEDING MAR. 1
CCC   FROM JAN. 1 (A LEAP YEAR DAY THUS BECOMES THE LAST DAY
CCC   OF THE YEAR.)  GIVEN DAY NUMBER AND ADJUSTED YEAR, RETURNS DAY,
CCC   MONTH, AND YEAR (CORRECTED).  DOES NOT CHECK PARAMETERS
CCC   FOR CONSISTENCY OR RANGE.
CCC
      INTEGER DAYNUM, AYEAR
      INTEGER DAY, YEAR
      INTEGER DAYTMP1, DAYTMP2
CCC
CCC   GETS MONTH AND DAY BY METHOD OF BINARY SEARCH.  SINCE THE
CCC   DATA ARE FIXED, THE APPROPRIATE BRANCHING IS WRITTEN INTO
CCC   THE LOGIC OF THE PROGRAM.
CCC
      DAYTMP1 = DAYNUM - 184
      IF (DAYTMP1.GT.0) GO TO 1010
C     FIRST HALF OF YEAR
      DAYTMP1 = DAYNUM - 92
      IF (DAYTMP1.GT.0) GO TO 1020
C     FIRST QUARTER OF YEAR
      DAYTMP1 = DAYNUM - 61
      IF (DAYTMP1.GT.0) GO TO 1030
C     MARCH OR APRIL
      DAYTMP 1 = DAYNUM - 31
      IF (DAYTMP1.GT.0) GO TO 1040
C     MARCH
      DAY = DAYNUM
      MONTH = 3
      GO TO 1050
C     APRIL
 1040 CONTINUE
      DAY = DAYTMP1
      MONTH = 4
      GO TO 1050
C     MAY
 1030 CONTINUE
      DAY = DAYTMP1
      MONTH = 5
      GO TO 1050
C     SECOND QUARTER OF YEAR
 1020 CONTINUE
      DAYTMP2 = DAYTMP1 - 61
      IF (DAYTMP2.GT.0) GOTO 1060
C     JUNE OR JULY
      DAYTMP2 = DAYTMP1 - 31
      IF (DAYTMP2.GT.0) GO TO 1070
C     JUNE
      DAY = DAYTMP1
      MONTH = 6
      GO TO 1050
C     JULY
 1070 CONTINUE
      DAY = DAYTMP2
      MONTH = 7
      GO TO 1050
C     AUGUST
 1060 CONTINUE
      DAY = DAYTMP2
      MONTH = 8
      GOTO 1050
C     SECOND HALF OF YEAR
 1010 CONTINUE
      DAYTMP2 = DAYTMP1 - 91
      IF (DAYTMP2.GT.0) GO TO 1080
C     THIRD QUARTER OF YEAR
      DAYTMP2 = DAYTMP1 - 61
      IF (DAYTMP2.GT.0) GO TO 1090
C     SEPTEMBER OR OCTOBER
      DAYTMP2 = DAYTMP1 - 30
      IF (DAYTMP2.GT.0) GO TO 1100
C     SEPTEMBER
      DAY = DAYTMP1
      MONTH = 9
      GO TO 1050
C     OCTOBER
 1100 CONTINUE
      DAY = DAYTMP2
      MONTH = 10
      GO TO 1050
C     NOVEMBER
 1090 CONTINUE
      DAY = DAYTMP2
      MONTH = 11
      GO TO 1050
C     FOURTH QUARTER OF YEAR
 1080 CONTINUE
      DAYTMP1 = DAYTMP2 - 62
      IF (DAYTMP1.GT.0) GO TO 1110
C     DECEMBER OR JANUARY
      DAYTMP1 = DAYTMP2 - 31
      IF (DAYTMP1.GT.0) GO TO 1120
C     DECEMBER
      DAY = DAYTMP2
      MONTH = 12
      GO TO 1050
C     JANUARY
 1120 CONTINUE
      DAY = DAYTMP1
      MONTH = 1
      GO TO 1050
C     FEBRUARY
 1110 CONTINUE
      DAY = DAYTMP1
      MONTH = 2
 1050 CONTINUE
CCC
CCC   YEAR IS ADJUSTED YEAR IF MONTH IS JANUARY OR FEBRUARY,
CCC   OTHERWISE PRECEDING YEAR
      YEAR = AYEAR
      IF (MONTH.GT.2) YEAR = YEAR - 1
      RETURN
      END
